name: Action CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run on my own container action 
        uses: ./
        with:
          who-to-greet: '@HVV83'